### ISSUE TITLE
Compatibility Problems

### ISSUE THREAD

**Issue by mushunrek** [adolgert/CTDE.jl#2]
Since the project has not updated for the last 8 years, it seems that it is not compatible with the Julia Package handling. I tried to use install as described in [the documentation](https://ctdejl.readthedocs.io/en/latest/install.html). The new way of doing should be
```julia
] add "https://github.com/adolgert/CTDE.jl.git"
```

But when doing so, the installation cannot finish as the repository is missing the necessary project files such as `Project.toml`.

I would be very glad to use the package, but I am rather new to julia and am not sure what parts have to be changed...

**Comment by adolgert** [comment]
Hi! I haven't updated this in a while because Sean Wu and I wrote something called CompetingClocks.jl that should be much more up to date. If you want to make a general agent-based simulation, Julia has a good Agents.jl and has a nice user experience. If you want to use semi-Markov exact stochastic methods, CompetingClocks.jl is a good bet.
